### PR TITLE
add enum for instrument types

### LINKED ISSUE #36: instrument type should be restricted to known instruments
Currently the instrument_type field is a string. It would be nice to restrict it to a known list of instruments for validation.

### PR DESCRIPTION
**Pull request by codeboten**
This will allow us to validate instrument types

Fixes #36

### CODE REVIEW

**Comment by tsloughter** [comment]
Won't this tie us to not supporting custom instruments in the configuration?

**Comment by codeboten** [comment]
Are custom instruments something we should support? I'm not sure how custom instruments would work w/ the API that lists the supported instruments

**Comment by jack-berg** [comment]
> Are custom instruments something we should support? I'm not sure how custom instruments would work w/ the API that lists the supported instruments

I don't know of any plans / discussions around custom instruments in the otel metrics API, so an enum seems appropriate.

**Comment by tsloughter** [comment]
Yea, nevermind, I was mixing up with custom aggregators.

:+1:

**Review by jack-berg — APPROVED** [review]
Slight preference for "*_up_down_*" over "*_updown_*"

**Comment by codeboten** [comment]
Looking at the spec, it appears either is ok. I'll open a PR against the spec to ensure consistency there as well.

**Comment by codeboten** [comment]
@jack-berg please have a look at https://github.com/open-telemetry/opentelemetry-specification/pull/3665

**Pull request merged**
