### PR TITLE
Drop anchors.yaml example

### LINKED ISSUE #19: Confirm yaml anchors can be extended
Currently in the example config, the following section exists:

https://github.com/open-telemetry/opentelemetry-configuration/blob/362b23ec9bb61537e6479a9546d7e8f8a388ec81/kitchen-sink-example.yaml#L95-L103

This configuration is intended to pull in the `otlp-exporter` configuration as an anchor, then add `temporality_preference` and `default_histogram_aggregation` to its configuration. However, I think those are currently applied to the `exporter` configuration and not the `otlp-exporter`.

Is this ok? I was under the impression that we would want to apply those to the otlp exporter block, rather than the exporter block.

### PR DESCRIPTION
**Pull request by jack-berg**
Resolves #19.

### CODE REVIEW

**Review by trask — APPROVED** [review]

**Review by marcalff — CHANGES_REQUESTED** [review]
```
[malff@malff-desktop opentelemetry-configuration]$ grep -R -l "<<:" *
examples/anchors.yaml
out/anchors.yaml
```

For completeness,
please remove the validation test `out/anchors.yaml`,
and adjust file `validator/shelltests/examples.test` accordingly.

**Comment by jack-berg** [comment]
>  please remove the validation test out/anchors.yaml,

This file isn't checked into version control

> and adjust file validator/shelltests/examples.test accordingly.

👍

**Review by marcalff — APPROVED** [review]
LGTM.

**Comment by marcalff** [comment]
> > please remove the validation test out/anchors.yaml,
> 
> This file isn't checked into version control
> 

Indeed, I got fooled by my local repo after a build, sorry about that.

**Pull request merged**
